project_id = "lcvdhtaqoumyokjqaqfw"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.pdf-api]
    verify_jwt = false
  [functions.s3-storage]
    verify_jwt = false
  [functions.scrape-branding]
    verify_jwt = false
  [functions.send-email]
    verify_jwt = false
  [functions.manage-user]
    verify_jwt = false
  [functions.invite-member]
    verify_jwt = false
