project_id = "lcvdhtaqoumyokjqaqfw"

[functions]
  [functions.pdf-api]
    verify_jwt = false
  [functions.s3-storage]
    verify_jwt = false
  [functions.scrape-branding]
    verify_jwt = false
  [functions.send-email]
    verify_jwt = false
  [functions.send-order-email]
    verify_jwt = false
  [functions.email-dispatcher]
    verify_jwt = false
  [functions.email-account-manage]
    verify_jwt = false
  [functions.request-password-reset]
    verify_jwt = false
  [functions.request-signup]
    verify_jwt = false
  [functions.manage-user]
    verify_jwt = false
  [functions.invite-member]
    verify_jwt = false
  [functions.invite-platform-admin]
    verify_jwt = false
  [functions.oauth-callback]
    verify_jwt = false
  [functions.cleanup-stale-drafts]
    verify_jwt = false
  [functions.submit-contact]
    verify_jwt = false
  [functions.detect-region]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
