version: '3.9'
services:
  api:
    build: .
    command: /app/scripts/start-api-dev.sh
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./storage:/app/storage
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker-heavy:
    build: .
    command: /app/scripts/start-worker-heavy.sh
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./storage:/app/storage
    depends_on:
      - redis

  worker-light:
    build: .
    command: /app/scripts/start-worker-light.sh
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./storage:/app/storage
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
