UPDATE public.product_options
SET values = jsonb_build_array(
  jsonb_build_object('label','No Tab Dividers','slug','no-tab-dividers','group','Tab Dividers','price_impact',0,'price_type','per_document','is_default',true,'metadata',jsonb_build_object()),
  jsonb_build_object('label','1 pack — up to 10 tabs (White)','slug','1-pack-up-to-10-tabs-white','group','Tab Dividers','price_impact',14.00,'price_type','per_document','is_default',false,'metadata',jsonb_build_object('tab_count',10,'pack_count',1,'pack_size',10,'color','white','material','card','printable',true)),
  jsonb_build_object('label','2 packs — up to 20 tabs (White)','slug','2-packs-up-to-20-tabs-white','group','Tab Dividers','price_impact',28.00,'price_type','per_document','is_default',false,'metadata',jsonb_build_object('tab_count',20,'pack_count',2,'pack_size',10,'color','white','material','card','printable',true)),
  jsonb_build_object('label','3 packs — up to 30 tabs (White)','slug','3-packs-up-to-30-tabs-white','group','Tab Dividers','price_impact',42.00,'price_type','per_document','is_default',false,'metadata',jsonb_build_object('tab_count',30,'pack_count',3,'pack_size',10,'color','white','material','card','printable',true)),
  jsonb_build_object('label','4 packs — up to 40 tabs (White)','slug','4-packs-up-to-40-tabs-white','group','Tab Dividers','price_impact',56.00,'price_type','per_document','is_default',false,'metadata',jsonb_build_object('tab_count',40,'pack_count',4,'pack_size',10,'color','white','material','card','printable',true)),
  jsonb_build_object('label','5 packs — up to 50 tabs (White)','slug','5-packs-up-to-50-tabs-white','group','Tab Dividers','price_impact',70.00,'price_type','per_document','is_default',false,'metadata',jsonb_build_object('tab_count',50,'pack_count',5,'pack_size',10,'color','white','material','card','printable',true)),
  jsonb_build_object('label','1 pack — up to 10 tabs (Multi-Colour)','slug','1-pack-up-to-10-tabs-multi-colour','group','Tab Dividers','price_impact',18.00,'price_type','per_document','is_default',false,'metadata',jsonb_build_object('tab_count',10,'pack_count',1,'pack_size',10,'color','multi','material','card','printable',true)),
  jsonb_build_object('label','2 packs — up to 20 tabs (Multi-Colour)','slug','2-packs-up-to-20-tabs-multi-colour','group','Tab Dividers','price_impact',36.00,'price_type','per_document','is_default',false,'metadata',jsonb_build_object('tab_count',20,'pack_count',2,'pack_size',10,'color','multi','material','card','printable',true)),
  jsonb_build_object('label','3 packs — up to 30 tabs (Multi-Colour)','slug','3-packs-up-to-30-tabs-multi-colour','group','Tab Dividers','price_impact',54.00,'price_type','per_document','is_default',false,'metadata',jsonb_build_object('tab_count',30,'pack_count',3,'pack_size',10,'color','multi','material','card','printable',true)),
  jsonb_build_object('label','4 packs — up to 40 tabs (Multi-Colour)','slug','4-packs-up-to-40-tabs-multi-colour','group','Tab Dividers','price_impact',72.00,'price_type','per_document','is_default',false,'metadata',jsonb_build_object('tab_count',40,'pack_count',4,'pack_size',10,'color','multi','material','card','printable',true)),
  jsonb_build_object('label','5 packs — up to 50 tabs (Multi-Colour)','slug','5-packs-up-to-50-tabs-multi-colour','group','Tab Dividers','price_impact',90.00,'price_type','per_document','is_default',false,'metadata',jsonb_build_object('tab_count',50,'pack_count',5,'pack_size',10,'color','multi','material','card','printable',true))
)
WHERE lower(name) = 'tab dividers';