INSERT INTO public.rate_card_finishing (scope_type, tenant_id, code, label, category, pricing_basis, variant, size, sell_price, cost_price, sort_order, is_active) VALUES
('master', NULL, 'comb-19mm', 'Comb Binding 19mm (TODO: price)', 'binding', 'per_unit', '19mm', NULL, 0, 0, 1000, true),
('master', NULL, 'comb-32mm', 'Comb Binding 32mm (TODO: price)', 'binding', 'per_unit', '32mm', NULL, 0, 0, 1010, true),
('master', NULL, 'comb-38mm', 'Comb Binding 38mm (TODO: price)', 'binding', 'per_unit', '38mm', NULL, 0, 0, 1020, true),
('master', NULL, 'comb-51mm', 'Comb Binding 51mm (TODO: price)', 'binding', 'per_unit', '51mm', NULL, 0, 0, 1030, true),
('master', NULL, 'spiral-6mm', 'Spiral Binding 6mm (TODO: price)', 'binding', 'per_unit', '6mm', NULL, 0, 0, 1040, true),
('master', NULL, 'spiral-12mm', 'Spiral Binding 12mm (TODO: price)', 'binding', 'per_unit', '12mm', NULL, 0, 0, 1050, true),
('master', NULL, 'spiral-20mm', 'Spiral Binding 20mm (TODO: price)', 'binding', 'per_unit', '20mm', NULL, 0, 0, 1060, true),
('master', NULL, 'spiral-25mm', 'Spiral Binding 25mm (TODO: price)', 'binding', 'per_unit', '25mm', NULL, 0, 0, 1070, true),
('master', NULL, 'spiral-32mm', 'Spiral Binding 32mm (TODO: price)', 'binding', 'per_unit', '32mm', NULL, 0, 0, 1080, true),
('master', NULL, 'wire-6mm', 'Twin Loop Wire 6mm (TODO: price)', 'binding', 'per_unit', '6mm', NULL, 0, 0, 1090, true),
('master', NULL, 'wire-16mm', 'Twin Loop Wire 16mm (TODO: price)', 'binding', 'per_unit', '16mm', NULL, 0, 0, 1100, true),
('master', NULL, 'wire-22mm', 'Twin Loop Wire 22mm (TODO: price)', 'binding', 'per_unit', '22mm', NULL, 0, 0, 1110, true),
('master', NULL, 'ring-binder-40mm', 'Ring Binder 40mm (TODO: price)', 'binding', 'per_unit', '40mm', NULL, 0, 0, 1120, true),
('master', NULL, 'ring-binder-65mm', 'Ring Binder 65mm (TODO: price)', 'binding', 'per_unit', '65mm', NULL, 0, 0, 1130, true),
('master', NULL, 'matte-pvc-cover-a4', 'Matte PVC Cover A4 (200µ) (TODO: price)', 'cover', 'per_sheet', 'matte', 'A4', 0, 0, 1140, true),
('master', NULL, 'frosted-pvc-cover-a4', 'Frosted PVC Cover A4 (300µ) (TODO: price)', 'cover', 'per_sheet', 'frosted', 'A4', 0, 0, 1150, true),
('master', NULL, 'card-back-black-a4', 'Card Back A4 (250gsm Black) (TODO: price)', 'cover', 'per_sheet', 'black', 'A4', 0, 0, 1160, true),
('master', NULL, 'card-back-navy-a4', 'Card Back A4 (250gsm Navy) (TODO: price)', 'cover', 'per_sheet', 'navy', 'A4', 0, 0, 1170, true),
('master', NULL, 'card-cover-160-a4', '160gsm White Card Cover A4 (TODO: price)', 'cover', 'per_sheet', '160gsm', 'A4', 0, 0, 1180, true),
('master', NULL, 'card-cover-250-a4', '250gsm White Card Cover A4 (TODO: price)', 'cover', 'per_sheet', '250gsm', 'A4', 0, 0, 1190, true),
('master', NULL, 'card-cover-300-a4', '300gsm White Card Cover A4 (TODO: price)', 'cover', 'per_sheet', '300gsm', 'A4', 0, 0, 1200, true),
('master', NULL, 'silk-cover-250-a4', '250gsm Silk Card Cover A4 (TODO: price)', 'cover', 'per_sheet', 'silk-250', 'A4', 0, 0, 1210, true),
('master', NULL, 'gloss-cover-250-a4', '250gsm Gloss Card Cover A4 (TODO: price)', 'cover', 'per_sheet', 'gloss-250', 'A4', 0, 0, 1220, true),
('master', NULL, 'matte-pvc-cover-a3', 'Matte PVC Cover A3 (200µ) (TODO: price)', 'cover', 'per_sheet', 'matte', 'A3', 0, 0, 1230, true),
('master', NULL, 'frosted-pvc-cover-a3', 'Frosted PVC Cover A3 (300µ) (TODO: price)', 'cover', 'per_sheet', 'frosted', 'A3', 0, 0, 1240, true),
('master', NULL, 'card-back-black-a3', 'Card Back A3 (250gsm Black) (TODO: price)', 'cover', 'per_sheet', 'black', 'A3', 0, 0, 1250, true),
('master', NULL, 'card-back-navy-a3', 'Card Back A3 (250gsm Navy) (TODO: price)', 'cover', 'per_sheet', 'navy', 'A3', 0, 0, 1260, true),
('master', NULL, 'card-cover-160-a3', '160gsm White Card Cover A3 (TODO: price)', 'cover', 'per_sheet', '160gsm', 'A3', 0, 0, 1270, true),
('master', NULL, 'card-cover-250-a3', '250gsm White Card Cover A3 (TODO: price)', 'cover', 'per_sheet', '250gsm', 'A3', 0, 0, 1280, true),
('master', NULL, 'card-cover-300-a3', '300gsm White Card Cover A3 (TODO: price)', 'cover', 'per_sheet', '300gsm', 'A3', 0, 0, 1290, true),
('master', NULL, 'silk-cover-250-a3', '250gsm Silk Card Cover A3 (TODO: price)', 'cover', 'per_sheet', 'silk-250', 'A3', 0, 0, 1300, true),
('master', NULL, 'gloss-cover-250-a3', '250gsm Gloss Card Cover A3 (TODO: price)', 'cover', 'per_sheet', 'gloss-250', 'A3', 0, 0, 1310, true),
('master', NULL, 'lamination-a6-gloss', 'Lamination A6 Gloss (TODO: price)', 'lamination', 'per_sheet', 'gloss', 'A6', 0, 0, 1320, true),
('master', NULL, 'lamination-a6-matt', 'Lamination A6 Matt (TODO: price)', 'lamination', 'per_sheet', 'matt', 'A6', 0, 0, 1330, true),
('master', NULL, 'lamination-a6-soft-touch', 'Lamination A6 Soft-Touch (TODO: price)', 'lamination', 'per_sheet', 'soft-touch', 'A6', 0, 0, 1340, true),
('master', NULL, 'lamination-a6-encapsulated', 'Lamination A6 Encapsulated (TODO: price)', 'lamination', 'per_sheet', 'encapsulated', 'A6', 0, 0, 1350, true),
('master', NULL, 'lamination-dl-gloss', 'Lamination DL Gloss (TODO: price)', 'lamination', 'per_sheet', 'gloss', 'DL', 0, 0, 1360, true),
('master', NULL, 'lamination-dl-matt', 'Lamination DL Matt (TODO: price)', 'lamination', 'per_sheet', 'matt', 'DL', 0, 0, 1370, true),
('master', NULL, 'lamination-dl-soft-touch', 'Lamination DL Soft-Touch (TODO: price)', 'lamination', 'per_sheet', 'soft-touch', 'DL', 0, 0, 1380, true),
('master', NULL, 'lamination-dl-encapsulated', 'Lamination DL Encapsulated (TODO: price)', 'lamination', 'per_sheet', 'encapsulated', 'DL', 0, 0, 1390, true),
('master', NULL, 'lamination-a5-gloss', 'Lamination A5 Gloss (TODO: price)', 'lamination', 'per_sheet', 'gloss', 'A5', 0, 0, 1400, true),
('master', NULL, 'lamination-a5-matt', 'Lamination A5 Matt (TODO: price)', 'lamination', 'per_sheet', 'matt', 'A5', 0, 0, 1410, true),
('master', NULL, 'lamination-a5-soft-touch', 'Lamination A5 Soft-Touch (TODO: price)', 'lamination', 'per_sheet', 'soft-touch', 'A5', 0, 0, 1420, true),
('master', NULL, 'lamination-a5-encapsulated', 'Lamination A5 Encapsulated (TODO: price)', 'lamination', 'per_sheet', 'encapsulated', 'A5', 0, 0, 1430, true),
('master', NULL, 'lamination-a4-soft-touch', 'Lamination A4 Soft-Touch (TODO: price)', 'lamination', 'per_sheet', 'soft-touch', 'A4', 0, 0, 1440, true),
('master', NULL, 'lamination-a4-encapsulated', 'Lamination A4 Encapsulated (TODO: price)', 'lamination', 'per_sheet', 'encapsulated', 'A4', 0, 0, 1450, true),
('master', NULL, 'lamination-sra3-gloss', 'Lamination SRA3 Gloss (TODO: price)', 'lamination', 'per_sheet', 'gloss', 'SRA3', 0, 0, 1460, true),
('master', NULL, 'lamination-sra3-matt', 'Lamination SRA3 Matt (TODO: price)', 'lamination', 'per_sheet', 'matt', 'SRA3', 0, 0, 1470, true),
('master', NULL, 'lamination-sra3-soft-touch', 'Lamination SRA3 Soft-Touch (TODO: price)', 'lamination', 'per_sheet', 'soft-touch', 'SRA3', 0, 0, 1480, true),
('master', NULL, 'lamination-sra3-encapsulated', 'Lamination SRA3 Encapsulated (TODO: price)', 'lamination', 'per_sheet', 'encapsulated', 'SRA3', 0, 0, 1490, true),
('master', NULL, 'lamination-a3-soft-touch', 'Lamination A3 Soft-Touch (TODO: price)', 'lamination', 'per_sheet', 'soft-touch', 'A3', 0, 0, 1500, true),
('master', NULL, 'lamination-a3-encapsulated', 'Lamination A3 Encapsulated (TODO: price)', 'lamination', 'per_sheet', 'encapsulated', 'A3', 0, 0, 1510, true),
('master', NULL, 'lamination-a2-gloss', 'Lamination A2 Gloss (TODO: price)', 'lamination', 'per_sheet', 'gloss', 'A2', 0, 0, 1520, true),
('master', NULL, 'lamination-a2-matt', 'Lamination A2 Matt (TODO: price)', 'lamination', 'per_sheet', 'matt', 'A2', 0, 0, 1530, true),
('master', NULL, 'lamination-a2-soft-touch', 'Lamination A2 Soft-Touch (TODO: price)', 'lamination', 'per_sheet', 'soft-touch', 'A2', 0, 0, 1540, true),
('master', NULL, 'lamination-a2-encapsulated', 'Lamination A2 Encapsulated (TODO: price)', 'lamination', 'per_sheet', 'encapsulated', 'A2', 0, 0, 1550, true),
('master', NULL, 'lamination-a1-gloss', 'Lamination A1 Gloss (TODO: price)', 'lamination', 'per_sheet', 'gloss', 'A1', 0, 0, 1560, true),
('master', NULL, 'lamination-a1-matt', 'Lamination A1 Matt (TODO: price)', 'lamination', 'per_sheet', 'matt', 'A1', 0, 0, 1570, true),
('master', NULL, 'lamination-a1-soft-touch', 'Lamination A1 Soft-Touch (TODO: price)', 'lamination', 'per_sheet', 'soft-touch', 'A1', 0, 0, 1580, true),
('master', NULL, 'lamination-a1-encapsulated', 'Lamination A1 Encapsulated (TODO: price)', 'lamination', 'per_sheet', 'encapsulated', 'A1', 0, 0, 1590, true),
('master', NULL, 'lamination-a0-gloss', 'Lamination A0 Gloss (TODO: price)', 'lamination', 'per_sheet', 'gloss', 'A0', 0, 0, 1600, true),
('master', NULL, 'lamination-a0-matt', 'Lamination A0 Matt (TODO: price)', 'lamination', 'per_sheet', 'matt', 'A0', 0, 0, 1610, true),
('master', NULL, 'lamination-a0-soft-touch', 'Lamination A0 Soft-Touch (TODO: price)', 'lamination', 'per_sheet', 'soft-touch', 'A0', 0, 0, 1620, true),
('master', NULL, 'lamination-a0-encapsulated', 'Lamination A0 Encapsulated (TODO: price)', 'lamination', 'per_sheet', 'encapsulated', 'A0', 0, 0, 1630, true),
('master', NULL, 'lamination-bc-gloss', 'Lamination BC Gloss (TODO: price)', 'lamination', 'per_sheet', 'gloss', NULL, 0, 0, 1640, true),
('master', NULL, 'lamination-bc-matt', 'Lamination BC Matt (TODO: price)', 'lamination', 'per_sheet', 'matt', NULL, 0, 0, 1650, true),
('master', NULL, 'lamination-bc-soft-touch', 'Lamination BC Soft-Touch (TODO: price)', 'lamination', 'per_sheet', 'soft-touch', NULL, 0, 0, 1660, true),
('master', NULL, 'lamination-bc-encapsulated', 'Lamination BC Encapsulated (TODO: price)', 'lamination', 'per_sheet', 'encapsulated', NULL, 0, 0, 1670, true),
('master', NULL, 'fold-gate', 'Gate-Fold (TODO: price)', 'folding', 'per_unit', 'gate', NULL, 0, 0, 1680, true),
('master', NULL, 'corners-round-3mm', 'Rounded Corners 3mm (TODO: price)', 'trimming', 'per_set', '3mm', NULL, 0, 0, 1690, true),
('master', NULL, 'corners-round-6mm', 'Rounded Corners 6mm (TODO: price)', 'trimming', 'per_set', '6mm', NULL, 0, 0, 1700, true),
('master', NULL, 'staple-corner', 'Corner Staple (TODO: price)', 'stapling', 'per_unit', 'corner', NULL, 0, 0, 1710, true),
('master', NULL, 'staple-double-edge', 'Double Staple Edge (TODO: price)', 'stapling', 'per_unit', 'double-edge', NULL, 0, 0, 1720, true),
('master', NULL, 'rubber-band', 'Collate & Rubber Band (TODO: price)', 'packaging', 'per_unit', 'rubber-band', NULL, 0, 0, 1730, true),
('master', NULL, 'shrink-wrap', 'Shrink Wrap (TODO: price)', 'packaging', 'per_unit', 'shrink', NULL, 0, 0, 1740, true),
('master', NULL, 'hole-punch-2', '2-Hole Punch (TODO: price)', 'hole_punching', 'per_unit', '2-hole', NULL, 0, 0, 1750, true),
('master', NULL, 'hole-punch-3', '3-Hole Punch (TODO: price)', 'hole_punching', 'per_unit', '3-hole', NULL, 0, 0, 1760, true),
('master', NULL, 'hole-punch-4', '4-Hole Punch (TODO: price)', 'hole_punching', 'per_unit', '4-hole', NULL, 0, 0, 1770, true),
('master', NULL, 'tab-pack-white', 'Tab Pack (10) — White (TODO: price)', 'tab_dividers', 'per_unit', 'white', NULL, 0, 0, 1780, true),
('master', NULL, 'tab-pack-multi', 'Tab Pack (10) — Multi-Colour (TODO: price)', 'tab_dividers', 'per_unit', 'multi', NULL, 0, 0, 1790, true),
('master', NULL, 'insert-slip-80', 'Blank Slip Sheet 80gsm White (TODO: price)', 'inserts', 'per_sheet', 'slip-80', NULL, 0, 0, 1800, true),
('master', NULL, 'insert-slip-160', 'Blank Slip Sheet 160gsm Card (TODO: price)', 'inserts', 'per_sheet', 'slip-160', NULL, 0, 0, 1810, true),
('master', NULL, 'insert-divider-colour', 'Coloured Divider Sheet (TODO: price)', 'inserts', 'per_sheet', 'divider', NULL, 0, 0, 1820, true),
('master', NULL, 'bc-foil-gold', 'Foil Stamping (Gold) (TODO: price)', 'special', 'per_set', 'foil-gold', NULL, 0, 0, 1830, true),
('master', NULL, 'bc-foil-silver', 'Foil Stamping (Silver) (TODO: price)', 'special', 'per_set', 'foil-silver', NULL, 0, 0, 1840, true),
('master', NULL, 'bc-foil-rose', 'Foil Stamping (Rose Gold) (TODO: price)', 'special', 'per_set', 'foil-rose', NULL, 0, 0, 1850, true),
('master', NULL, 'bc-spot-uv-front', 'Spot UV (Front) (TODO: price)', 'special', 'per_set', 'spot-uv-front', NULL, 0, 0, 1860, true),
('master', NULL, 'bc-spot-uv-both', 'Spot UV (Both Sides) (TODO: price)', 'special', 'per_set', 'spot-uv-both', NULL, 0, 0, 1870, true),
('master', NULL, 'bc-emboss', 'Embossing (TODO: price)', 'special', 'per_set', 'emboss', NULL, 0, 0, 1880, true),
('master', NULL, 'bc-letterpress', 'Letterpress (1 colour) (TODO: price)', 'special', 'per_set', 'letterpress', NULL, 0, 0, 1890, true);